spr# Nome da aplicação
spring.application.name=catalogolivros

# Conexão com o banco
spring.datasource.url=jdbc:mysql://localhost:3306/catalogo

spring.datasource.username=root
spring.datasource.password=Gabuy741!!

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuração do Hibernate
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect